[platformio]
src_dir = firmware

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<firmware.ino>
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.2.1
  adafruit/DHT sensor library@^1.4.6
  adafruit/Adafruit Unified Sensor@^1.1.15
  olikraus/U8g2@^2.35.30
